[project]
authors = ["Mehmet Efe Akça <efeakca@gmail.com>"]
channels = ["conda-forge", "pyg"]
description = "Add a short description here"
name = "Code"
platforms = ["osx-arm64"]
version = "0.1.0"

[pypi-options]
index-url = "https://pypi.org/simple"
no-build-isolation = ["torch_scatter", "torch_cluster", "torch_sparse", "torch"]
find-links = [{url = "https://pytorch-geometric.com/whl/torch-2.4.0%2Bcpu.html"}]

[tasks]

[dependencies]
python = "3.10.*"
numpy = ">=2.1.3,<3"
scipy = ">=1.14.1,<2"
matplotlib = ">=3.9.2,<4"
pip = ">=24.3.1,<25"
ipython = ">=8.29.0,<9"
pytorch = ">=2.4.1,<3"
torchvision = ">=0.19.1,<0.20"
torchaudio = ">=2.4.1,<3"
pyg = ">=2.6.1,<3"
scikit-fmm = ">=2024.9.16,<2025"
scikit-learn = ">=1.5.2,<2"
pandas = ">=2.2.3,<3"

[pypi-dependencies]
networkx = "*"
obspy = ">=1.4.1, <2"
cvxpy = ">=1.5.3, <2"
h5py = ">=3.12.1, <4"
pyyaml = ">=6.0.2, <7"
torch = "*"
torch-scatter = ">=2.1.2, <3"
torch-cluster = ">=1.6.3, <2"
torch-sparse = ">=0.6.18, <0.7"
# torch-scatter = ">=2.1.2, <3"
# torch-cluster = ">=1.6.3, <2"
# torch-sparse = ">=0.6.18, <0.7"
